apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels: {}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "JAVA_OPTIONS"
          value: "-Xms512m -Xmx512m"