spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms512m -Xmx512m -Dspring.profiles.active=${spring-boot.activeProfiles}  -Djava.net.preferIPv4Stack=true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10