kind: ConfigMap
apiVersion: v1
metadata:
  name: brewing
data:
  application.yaml: |-
    logging:
      level.org.springframework.cloud: INFO
      level.org.springframework.cloud.sleuth: ERROR
      level.org.springframework.cloud.sleuth.log: ERROR
      level.org.springframework.cloud.sleuth.trace: ERROR
      level.org.springframework.cloud.sleuth.instrument.rxjava: ERROR

    server:
      port: 8080

    ribbon:
      eureka:
        enabled: false
      client:
        enabled: true

    spring:
      rabbitmq:
        host: rabbitmq-client
      sleuth:
        enabled: false
    zipkin:
      store:
        type: mem