kind: ConfigMap
apiVersion: v1
metadata:
  name: brewing
data:
  application.yaml: |-
    server:
      port: 8080
      tomcat:
        max-threads: 10
    spring:
      sleuth:
        web:
          skipPattern: /api-docs.*|/autoconfig|/health|/configprops|/dump|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/feed/process/.*
      cloud:
        stream:
          artemis:
            binder:
              transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
              host: artemis-client
              port: 61616
      artemis:
        mode: native
        host: artemis-client


    hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

    endpoints.health.sensitive: false

    eureka:
      client:
        enabled: false

    ribbon:
      eureka:
        enabled: false
      client:
        enabled: false
