server.port: 8080

spring.rabbitmq.host: ${RABBITMQ_CLIENT_SERVICE_HOST}

eureka:
  numberRegistrySyncRetries: 0
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: "http://eureka/eureka"
  server:
    enableSelfPreservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    non-secure-port-enabled: true
    non-secure-port: 80
    hostname: eureka