server.port: 8080
spring.rabbitmq.host: rabbitmq-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/
  instance:
    hostname: brewing
    nonSecurePort: 8080
    preferIpAddress: false

ribbon:
  eureka:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

spring.cloud.stream:
  binder.rabbit.default.maxConcurrency: 5

endpoints.health.sensitive: false

logging:
  level.org.springframework.cloud: INFO
  level.org.springframework.cloud.sleuth: ERROR
  level.org.springframework.cloud.sleuth.log: ERROR
  level.org.springframework.cloud.sleuth.trace: ERROR
  level.org.springframework.cloud.sleuth.instrument.rxjava: ERROR

