spring.application.name: presenting

logging:
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG

server.port: 8080

spring.rabbitmq.host: ${RABBIT_HOST:localhost}
spring.sleuth.web.skipPattern: /api-docs.*|/autoconfig|/health|/configprops|/dump|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/feed/process/.*

logging.file: build/presenting.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000


endpoints.health.sensitive: false
