spring.application.name: presenting

server.port: 8080

spring.rabbitmq.host:

spring.rabbitmq.host: ${RABBITMQ_CLIENT_SERVICE_HOST}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST}/eureka/


