---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 391fda7ba3d7f093e3b38146079104905059afa4
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: openshift
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: reporting
      version: 1.0-SNAPSHOT
      group: io.spring.cloud.samples.brewery
    name: reporting
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      project: reporting
      provider: fabric8
      group: io.spring.cloud.samples.brewery
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 391fda7ba3d7f093e3b38146079104905059afa4
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: openshift
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=reporting&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: reporting
      version: 1.0-SNAPSHOT
      group: io.spring.cloud.samples.brewery
    name: reporting
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: reporting
        provider: fabric8
        group: io.spring.cloud.samples.brewery
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 391fda7ba3d7f093e3b38146079104905059afa4
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: openshift
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=reporting&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: reporting
          version: 1.0-SNAPSHOT
          group: io.spring.cloud.samples.brewery
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=ocp
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_APP_DIR
            value: /deployments
          image: reporting:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
