spring.application.name: zipkin

logging:
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG

server.port: 8080

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  sleuth:
    enabled: false
zipkin:
  store:
    type: mem

logging.file: build/zipkin-server.log


endpoints.health.sensitive: false
