kind: ConfigMap
apiVersion: v1
metadata:
  name: presenting
data:
  application.yaml: |-
    server.port: 8080
    spring:
      rabbitmq:
        host: rabbitmq-client
      sleuth:
        web:
          skipPattern: /api-docs.*|/autoconfig|/health|/configprops|/dump|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/feed/process/.*
      cloud:
        stream:
          binder:
            rabbit.default.maxConcurrency: 5

    hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

    endpoints.health.sensitive: false

    eureka:
      client:
        enabled: false

    ribbon:
      eureka:
        enabled: false

    logging:
     level.org.springframework.cloud: INFO
     level.org.springframework.cloud.sleuth: ERROR
     level.org.springframework.cloud.sleuth.log: ERROR
     level.org.springframework.cloud.sleuth.trace: ERROR
     level.org.springframework.cloud.sleuth.instrument.rxjava: ERROR
