- name: springboot-ocp
  generator:
    includes:
      - spring-boot
    config:
      env:
        JAVA_OPTIONS: "-Dspring.profiles.active=ocp"
  enricher:
    includes:
      - fmp-controller
      - fmp-service
