kind: ConfigMap
apiVersion: v1
metadata:
  name: zuul
data:
  application.yaml: |-
    server:
      port: 8080
      tomcat:
        max-threads: 10
    spring:
      cloud:
        stream:
          artemis:
            binder:
              transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
              host: artemis-client
              port: 61616
      artemis:
        mode: native
        host: artemis-client

    hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

    endpoints.health.sensitive: false
