kind: ConfigMap
apiVersion: v1
metadata:
  name: zuul
data:
  application.yaml: |-
    server.port: 8080
    spring:
      rabbitmq:
        host: rabbitmq-client
      cloud:
        stream:
          binder:
            rabbit.default.maxConcurrency: 5

    hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

    endpoints.health.sensitive: false

    brewing.ribbon.listOfServers: brewing:8080
    ingredients.ribbon.listOfServers: ingredients:8080
    presenting.ribbon.listOfServers: presenting:8080
    reporting.ribbon.listOfServers: reporting:8080
    zuul.ribbon.listOfServers: zuul:8080

    logging:
     level.org.springframework.cloud: INFO
     level.org.springframework.cloud.sleuth: ERROR
     level.org.springframework.cloud.sleuth.log: ERROR
     level.org.springframework.cloud.sleuth.trace: ERROR
     level.org.springframework.cloud.sleuth.instrument.rxjava: ERROR
