server.port: 8080

spring.zipkin.enabled: false

spring:
  application:
    name: config-server
  rabbitmq:
    host: rabbitmq-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kameshsampath/brewery-config.git
          timeout: 10
