##################################################################################################
#  Apache Artemis
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: apache-artemis
  labels:
    app: apache-artemis
spec:
  ports:
  - port: 61616
    name: tcp
  selector:
    app:  apache-artemis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  apache-artemis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  apache-artemis
        version: "2.1.0"
    spec:
      containers:
      - image: kameshsampath/apache-artemis:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 61616
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 5
        name: apache-artemis
        ports:
        - containerPort: 8161
          name: http
          protocol: TCP
        - containerPort: 61616
          name: amqp
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 61616
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        securityContext:
          privileged: false

